export const ERP_ITEM_FIELDS = [
  { id: 'filial', label: 'Filial (ERP)', type: 'text' },
  { id: 'numero_sc', label: 'Número da SC', type: 'text' },
  { id: 'item_sc', label: 'Item da SC', type: 'text' },
  { id: 'produto_id', label: 'Produto', type: 'text' },
  { id: 'descricao', label: 'Descrição (ERP)', type: 'text' },
  { id: 'tipo', label: 'Tipo (ERP)', type: 'text' },
  { id: 'segunda_unid', label: 'Segunda Unid', type: 'text' },
  { id: 'unid_med', label: 'Unid Med', type: 'text' },
  { id: 'quantidade', label: 'Quantidade (ERP)', type: 'numeric' },
  { id: 'qtd_2a', label: 'Qtd. 2a', type: 'numeric' },
  { id: 'data_necessidade', label: 'Necessidade (ERP)', type: 'text' },
  { id: 'armazem', label: 'Armazém', type: 'text' },
  { id: 'localizacao', label: 'Localização', type: 'text' },
  { id: 'observacao', label: 'Observação', type: 'text' },
  { id: 'dt_emissao', label: 'DT Emissão', type: 'text' },
  { id: 'centro_custo', label: 'Centro de Custo', type: 'text' },
  { id: 'ordem_producao', label: 'Ordem Produção', type: 'text' },
  { id: 'conta_contabil', label: 'Conta Contábil', type: 'text' },
  { id: 'item_contabil', label: 'Item Contábil', type: 'text' },
  { id: 'num_cotacao', label: 'Num. Cotação', type: 'text' },
  { id: 'solicitante', label: 'Solicitante (ERP)', type: 'text' },
  { id: 'fornecedor', label: 'Fornecedor', type: 'text' },
  { id: 'quant_entregue', label: 'Quant. Entregue', type: 'numeric' },
  { id: 'ok_status', label: 'Ok Status', type: 'text' },
  { id: 'transmissao', label: 'Transmissão', type: 'text' },
  { id: 'unid_1', label: 'Unid. 1', type: 'text' },
  { id: 'loja_fornecedor', label: 'Loja', type: 'text' },
  { id: 'classificacao', label: 'Classificação', type: 'text' },
  { id: 'fabricante', label: 'Fabricante', type: 'text' },
  { id: 'num_pedido', label: 'Num. Pedido', type: 'text' },
  { id: 'num_solic', label: 'Num. Solicit', type: 'text' },
  { id: 'nome_solicitante', label: 'Nome Solicitante', type: 'text' },
  { id: 'grupo_compras', label: 'Gr. Compras', type: 'text' },
  { id: 'item_pedido', label: 'Item Pedido', type: 'text' },
  { id: 'cod_cliente', label: 'Cod. Cliente', type: 'text' },
  { id: 'identificador', label: 'Identificador', type: 'text' },
  { id: 'num_os', label: 'Num. OS', type: 'text' },
  { id: 'tipo_operacao', label: 'Tipo Operação', type: 'text' },
  { id: 'cod_unidade', label: 'Cod. Unidade', type: 'text' },
  { id: 'qtd_seq', label: 'Qtd. Seq', type: 'text' },
  { id: 'seq_mrp', label: 'Seq MRP', type: 'text' },
  { id: 'rotina', label: 'Rotina', type: 'text' },
  { id: 'ger_proc', label: 'Ger. Proc', type: 'text' },
  { id: 'grupo', label: 'Grupo', type: 'text' },
  { id: 'elim_res', label: 'Elim. Res', type: 'text' },
  { id: 'tipo_entrada', label: 'Tipo Entrada', type: 'text' },
  { id: 'qtd_orig', label: 'Qtd. Orig', type: 'text' },
  { id: 'cod_prod', label: 'Cod. Prod', type: 'text' },
  { id: 'filial_entrega', label: 'Filial Entrega', type: 'text' },
  { id: 'preco_estimado', label: 'Preço Estimado', type: 'numeric' },
  { id: 'cond_pagto', label: 'Cond. Pagto', type: 'text' },
  { id: 'cod_oper', label: 'Cod. Oper', type: 'text' },
  { id: 'preco_unitario', label: 'Preço Unitário', type: 'numeric' },
  { id: 'valor_total', label: 'Valor Total', type: 'numeric' },
  { id: 'especie', label: 'Espécie', type: 'text' },
  { id: 'flag_alt', label: 'Flag Alt', type: 'text' },
  { id: 'gera_cp', label: 'Gera CP', type: 'text' },
  { id: 'moeda', label: 'Moeda', type: 'text' },
  { id: 'cod_local', label: 'Cod. Local', type: 'text' },
  { id: 'item_grade', label: 'Item Grade', type: 'text' },
  { id: 'grade', label: 'Grade', type: 'text' },
  { id: 'reemissao', label: 'Reemissão', type: 'text' },
  { id: 'nome', label: 'Nome (ERP)', type: 'text' },
  { id: 'tipo_solic', label: 'Tipo Solic', type: 'text' },
  { id: 'modalidade', label: 'Modalidade', type: 'text' },
  { id: 'tipo_mov', label: 'Tipo Mov', type: 'text' },
  { id: 'usr_mutal', label: 'Usr Mutal', type: 'text' },
  { id: 'num_orcamento', label: 'Num. Orçamento', type: 'text' },
  { id: 'ctr_custo', label: 'Ctr Custo', type: 'text' },
  { id: 'cod_estoque', label: 'Cod. Estoque', type: 'text' },
  { id: 'nr_projeto', label: 'Nr. Projeto', type: 'text' },
  { id: 'rateio', label: 'Rateio', type: 'text' },
  { id: 'programada', label: 'Programada', type: 'text' },
  { id: 'acc', label: 'ACC', type: 'text' },
  { id: 'sol_alt', label: 'Sol. Alt', type: 'text' },
  { id: 'item_alt', label: 'Item Alt', type: 'text' },
  { id: 'rev_estoque', label: 'Rev. Estoque', type: 'text' },
  { id: 'item_origem', label: 'Item Origem', type: 'text' },
  { id: 'centralizacao', label: 'Centralização', type: 'text' },
  { id: 'atualizacao', label: 'Atualização', type: 'text' },
  { id: 'filial_origem', label: 'Filial Origem', type: 'text' },
  { id: 'sc_origem', label: 'SC Origem', type: 'text' },
  { id: 'id_aps', label: 'ID APS', type: 'text' },
  { id: 'prod_res', label: 'Prod Res', type: 'text' },
  { id: 'data_aprov', label: 'Data Aprov', type: 'text' },
  { id: 'drp_necess', label: 'DRP Necess', type: 'text' },
  { id: 'nr_bordero', label: 'Nr. Borderô', type: 'text' },
  { id: 'aprovador', label: 'Aprovador', type: 'text' },
  { id: 'comprador', label: 'Comprador (Item)', type: 'text' },
  { id: 'tipo_cont', label: 'Tipo Cont', type: 'text' },
  { id: 'ped_venda', label: 'Ped. Venda', type: 'text' },
  { id: 'usr_canc', label: 'Usr. Canc', type: 'text' },
  { id: 'dt_canc', label: 'Dt. Canc', type: 'text' },
  { id: 'prod_interno', label: 'Prod. Interno', type: 'text' },
  { id: 'vlr_atu', label: 'Vlr. Atu', type: 'numeric' },
  { id: 'seq_sdc', label: 'Seq. SDC', type: 'text' },
  { id: 'dt_fim_prod', label: 'Dt Fim Prod', type: 'text' },
  { id: 'dt_ini_prod', label: 'Dt Ini Prod', type: 'text' },
  { id: 'hr_fim', label: 'Hr Fim', type: 'text' },
  { id: 'hr_ini', label: 'Hr Ini', type: 'text' },
  { id: 'status', label: 'Status (ERP)', type: 'text' },
  { id: 'prefixo', label: 'Prefixo', type: 'text' },
  { id: 'contr_loc', label: 'Contr Loc', type: 'text' },
  { id: 'grupo_item', label: 'Grupo Item', type: 'text' },
]
